### ISSUE TITLE
Django project template

### ISSUE THREAD

**Issue by joke2k** [joke2k/django-environ#138]
Create a django project template with settings.py that uses `.env` example file.

**Comment by mixkorshun** [comment]
I have made a simple project template with `django-environ`.

You can find it at: https://github.com/mixkorshun/django-environ-project-template
And you can read a tutorial here: https://github.com/mixkorshun/django-environ-project-template/wiki/README

I tried to make it directly in `django-environ` package, but faced the fact that creating a project with this template is not simple to describe. It happens because django requires you to write a full path to project template directory or url to archive.

**Comment by joke2k** [comment]
https://github.com/pydanny/cookiecutter-djangopackage is a good project template that uses django-environ
