### ISSUE TITLE
Any plan to support .toml format env file?

### ISSUE THREAD

**Issue by wahello** [joke2k/django-environ#224]
### Any plan to support .toml format env file?  Thanks!

**Comment by pataquets** [comment]
*If* any other configuration format were to be added, I'd rather vote for adding YAML.

IMO, it's more widespread and more familiar to most users. Disclaimer: only based on my own experience, of course. But, since I rarely find TOML files on my daily work, I assume it's less common. I guess I'd have to double-check syntax when writing any TOML, as opposed to a YAML, which I can write by heart, but just me.

Notice YAML has also quite a powerful logic in the parsing, allowing reuse, inclusion, etc. (not sure about TOML). Anyway, keep in mind that my main point it's about its widespread use. I don't want this issue to become a comparison about the pros/cons of both formats (other than ubiquity/popularity to most users). Format familiarity for users is as important as feature set, IMO.

Anyway, I'd love to hear why TOML in the first place, in case I'm missing something. Happy to learn :smile:

**Comment by webknjaz** [comment]
@pataquets I'd say that bringing PyYAML as a dependency is expensive. It is very heavy and probably not worth it. TOML can be a better choice because it encourages simpler syntax in many cases and has less hidden surprise behaviors. It's also a part of stdlib since Python 3.11 so an optional dependency (`tomlli`) is only needed to support older Pythons. From the maintenance perspective, this would be easier. Besides, there's a lot of TOML presence in the Python ecosystem these days. In particular, the packaging ecosystem is standardized around it for the past 9 years (PEP 517). A lot of linters (`pylint`, `ruff`) and workflow tools (`Hatch`, `towncrier`, `tox`) use TOML as a replacement for their INI-based configuration files.

PyYAML, OTOH, brings in `cffi` and other bits that are known to be difficult to maintain.

I should note, though, that dotenv is an accepted format across multiple ecosystems beyond Python. So introducing anything additional would create divergence and extra maintenance connected to the need of keeping the feature parity. Looking into the activity in the repo, I think it would only be sustainable if somebody were to step up and help the maintainer with the support work consistently.

**Comment by sergeyklay** [comment]
Hi there,

Apologies for the delay in getting back to you; it's taken me some time to find the opportunity to carefully consider this request.

Unfortunately, I’ll have to decline adding support for additional formats, as it would significantly complicate the project and increase maintenance costs. This includes functional parity, testing, documentation, dependency updates, and more.

Our focus remains on supporting the format specified in the project name: environment files (.env). The project was originally designed for .env files specifically, and expanding support to other formats like YAML or TOML could shift user expectations and project perception away from this focus.

In the Python ecosystem, powerful tools already exist to handle YAML and TOML (e.g., pyyaml and tomllib). Adding these formats to django-environ would effectively duplicate functionality that users are likely already covering with other libraries.

Supporting multiple formats would also mean extra testing, more frequent dependency updates, and constant attention to compatibility, which introduces risk for errors and technical debt. Furthermore, different formats may end up with varying levels of feature support, creating an inconsistency that could inconvenience users and reduce flexibility.

I regret having to turn down this request, but this decision is driven by the need to maintain a clear focus on stability and reliability.

Thank you for your understanding, and please don’t hesitate to reach out with any further questions.

Best regards,

**Comment by pataquets** [comment]
My preference for YAML was very conditional to the convenience of adding support for _any_ other format (notice the initial "If" on my comment).
After reading @webknjaz response, I've learnt quite a bunch of things about TOML which I wasn't aware of, such Python support and specially its apparent ubiquity on the Python ecosystem. It made me think twice and question about YAML being the best option. Thank you very much @webknjaz for the kind and detailed explanation!
Finally, after @sergeyklay's explanation, it becomes obvious to me that none of them is a good option (or any other whatsoever), due to the cited maintainability, testing and effort increase for no obvious gain, as already hinted by @webknjaz with the not-so-obvious-to-me size increase.
Keeping scope and complexity down is always desirable, and for this package, simplicity and lightweight are among its main features, so turning down the feature seems now to me the right choice. Anyway, thank you @sergeyklay for considering.
