### ISSUE TITLE
Pycharm user request

### ISSUE THREAD

**Issue by adamkeinan** [joke2k/django-environ#257]
apparently Pycharm uses one or even few ways to set the path variables. by using django-environ i solved the global variables issues regarding working working with various platform on the same project.
i noticed that also in atom some variables are conflicted even after deletion or setting.
some i dont want to delete.
my suggestion is if it possible to use a declaration or another evn. to create some loop between similar environments,so i wont have to switch scripts or workflows.

**Comment by sergeyklay** [comment]
I'm sorry, but I did not understand anything, haha. Sounds like a request to add new functionality related to your workflow? 
Anyway I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
