### ISSUE TITLE
Complex format in env variables 

### ISSUE THREAD

**Issue by dsever** [joke2k/django-environ#300]
Hi, 

I would like to use help from the community for our problem, we have SAML module that is expecting a little bit complex configuration format as:

```py
 DD_SAML2_ATTRIBUTES_MAP=(dict, {
        # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'Email': ('email', ),
        'UserName': ('username', ),
        'Firstname': ('first_name', ),
        'Lastname': ('last_name', )
    }),
```
But we are facing the problem, we can't find proper way how to register linux env variable to be parsed into format above, so any help would me useful.

Thanks

**Comment by jonprindiville** [comment]
I know that it is possible to get a dict that maps string->list by doing the following:

```
# in your environment
COMPLEX_DICT="key1=list-item1;key2=list-item1,list-item2;"
```

```
# in Python
env.dict('COMPLEX_DICT', cast={"value": list}, default={})
```

Note the dict being passed to `cast=` ☝️.  The resulting dict would be:

    {
        "key1": ["list-item1"],
        "key2": ["list-item1", "list-item2"],
    }

---

If you definitely need tuples and not list, then maybe this kind of thing works for you if you do `cast={"value": tuple}` in the call to `env.dict` instead of how my example uses `list`.

(FWIW, I discovered the `{"value": list}` thing while reading [the source](https://github.com/joke2k/django-environ/blob/027b2ef9d7000ce70aafd38b578ad1adb688d78b/environ/environ.py#L323-L333). I was just looking around in issues/PRs for any documentation about it 😄 that's how I encountered your issue)

**Comment by sergeyklay** [comment]
This was covered by https://github.com/joke2k/django-environ/pull/344. Thank you for the contributing, and for helping us make django-environ better.
