### ISSUE TITLE
EMAIL_USE_TLS and EMAIL_USE_SSL have no default value

### ISSUE THREAD

**Issue by jgadelange** [joke2k/django-environ#74]
My config broke when upgrading to version 0.4.0 because I had `EMAIL_USE_TLS = email_config['EMAIL_USE_TLS']` in my settings file and that key does not exist when no tls is defined.

I think this should default to `False`, as wel as the `EMAIL_USE_SSL` entry.

Otherwise it would be a good idea to document how to use the `email_url` in your settings.

**Comment by sergeyklay** [comment]
To set default values for a non existent variable use the following approach:

```python
import environ

env = environ.Env(
    # set casting, default value
    EMAIL_USE_TLS=(bool, False)
)

environ.Env.read_env('/path/to/.env')

EMAIL_USE_TLS = env('EMAIL_USE_TLS')
```

**Comment by jgadelange** [comment]
@sergeyklay I understand that that is how to set a default value. However I believe `EMAIL_USE_TLS`/`EMAIL_USE_SSL` should be configured through the `EMAIL_URL` setting. So adding sepparate `EMAIL_USE_TLS`/`EMAIL_USE_SSL` env vars doesn't feel like the solution here (especially since sometimes the value is filled from `EMAIL_URL`).

I would still say that there should be a default value (or some documentation on how the `email_url()` method can be used (wouldn't be bad anyway)).

**Comment by pataquets** [comment]
As of current version and from my understanding of the email configuration, the `EMAIL_URL` variable is the preferred method for configuration, at least in the vast majority of scenarios (I can't think about one which doesn't, but feel free to provide one for completeness).

So, from the above assumption, I see no need to read any `EMAIL_*` variables already covered by `EMAIL_URL`, which is what I'm currently doing (feedback is welcome). I just read `EMAIL_URL` in my `settings.py` and there are no other `EMAIL_*` variable references.
And since the email URL parsing will set TLS/SSL to match the URL schema accordingly (`smtp`, `smtps`, `smtp+tls`, etc.) this will be good to go.

Even more, I'm afraid that me manually setting any defaults for `EMAIL_TLS` or any other parameter would just be overriding/shadowing Django's defaults, which might change in the future. Unverified, not real example, just for illustration: imagine `EMAIL_SSL` going from `None` to `False` when SSL started being discouraged due to insecurity, long ago.

Just dropping this for the record and documenting what I'm assuming is current recommended usage.
/cc @joke2k : do you think anything above would be worth adding to docs? Lmk and I'll gladly do it.
