### ISSUE TITLE
support for inheritance in env

### ISSUE THREAD

**Issue by mwaaas** [joke2k/django-environ#82]
support such that I have multiple environment files,
- base
- development
- staging
- production

base to have common variables
and the rest to have specific variables and also have all base variables and can also override base variable

**Comment by bittner** [comment]
@mwaaas Sounds like you're looking  for [django-configurations](https://github.com/jazzband/django-configurations/#django-configurations).

If you keep everything that is not confidential in the source code, and _only_ put _confidential_ stuff into the environment (i.e. `.env` file), will you still need multiple environment files?

.env is not source code (keep it small!)
------------------

As I understand it, the `.env` file is really just a handy way to push string values into your application's process environment. If you maintain several `.env` files you probably also plan to put them under version control. I think that's not what the authors of this app would see as appropriate.

(Though I must admit, generally I prefer to have _everything_ under version control, too. Privately, locked down, if needed. Because _"what is not under version control doesn't exist"_.  Probably a matter of taste.)

**Comment by sergeyklay** [comment]
The main idea behind this project is to operate a simple env file containing key-value pairs. Implementing inheritance is beyond the scope of this project. I'm sorry, this won't be implemented.
