### ISSUE TITLE
support lower case options

### ISSUE THREAD

**Issue by oppianmatt** [joke2k/django-environ#87]
Some backends use lowercase options. For example https://github.com/django-pylibmc/django-pylibmc

```
CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': 'localhost:11211',
        'TIMEOUT': 500,
        'BINARY': True,
        'OPTIONS': {  # Maps to pylibmc "behaviors"
            'tcp_nodelay': True,
            'ketama': True
        }
    }
}
```

So I create a protocol on the fly like so in settings:

```
environ.Env.CACHE_SCHEMES['django-pylibmc'] = 'django_pylibmc.memcached.PyLibMCCache'
```

and set my environment like so:

```
CACHE_URL=django-pylibmc://memcached:11211?tcp_nodelay=1&ketama=1
```

But it get's converted to uppercase like so:

```
opt = {k.upper(): _cast_int(v[0])}
```

**Comment by joke2k** [comment]
Actually we cannot skip the use of upper() for keys.
Most of third-party plugin uses upper-cased characters.

See #139 if you are interested to extend django-environ

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) The issue #139 explains the acceptable way to handle such use cases. If anyone wants to get started, I'd love that.
